version: "3.8"

services:
  earnapp:
    image: ghcr.io/rezanb111/earnapp-proxy:latest
    container_name: earnapp
    restart: always
    environment:
      - EARNAPP_UUID=${EARNAPP_UUID:-}
      - PROXY=${PROXY:-}
    volumes:
      - earnapp-data:/etc/earnapp
    mem_limit: 256m

volumes:
  earnapp-data:
