version: "3.8"

services:
  taghie:
    image: ghcr.io/rezanb111/taghie:latest
    container_name: taghie
    restart: always
    environment:
      - CHAT_ID=${CHAT_ID}
      - EARNAPP_UUID=${EARNAPP_UUID:-}
      - PROXY=${PROXY:-}
    volumes:
      - taghie-data:/etc/earnapp
    mem_limit: 256m

volumes:
  taghie-data:
